export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const IS_LOADING = 'IS_LOADING';

export type _AUTHENTICATED = typeof AUTHENTICATED;
export type _NOT_AUTHENTICATED = typeof NOT_AUTHENTICATED;
export type _IS_LOADING = typeof IS_LOADING;
