export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export type _AUTHENTICATED = typeof AUTHENTICATED;
export type _NOT_AUTHENTICATED = typeof NOT_AUTHENTICATED;
